apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    osInfo: ubuntu,20.04,amd64
  labels:
    tanzuKubernetesRelease: v1.22.5---vmware.1-tkg.1-zshippable
    tkg.tanzu.vmware.com/cluster-name: testcluster
  name: vsphere-workload-cluster1
  namespace: namespace-test1
spec:
  clusterNetwork:
    apiServerPort: 443
    pods:
      cidrBlocks:
      - 10.10.10.10/18
    services:
      cidrBlocks:
      - 10.10.10.10/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: testcluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: testcluster
  topology:
    class: tkg-vsphere-default
    controlPlane:
      replicas: 1
    variables:
    - name: proxy
      value:
        caCert: "ProxycaCert"
        httpProxy: http://10.0.200.100
        httpsProxy: http://10.0.200.100
        noProxy:
        - .svc.cluster.local
        - 10.0.0.0/16
        - 169.254.0.0/16
    - name: location
      value: westus
    - name: clusterPlan
      value: devcc
    - name: tkgClusterRole
      value: "tkgClusterRole"
    - name: tkgCustomImage
      value:
        repository: "repository"
        caCert: "caCert"
        skpTlsVerify: true
    - name: resourceGroup
      value: azure-resource-group
    - name: subscriptionID
      value: 6c2a2ce1-649f-9d9k-a19c-c729h3cf6126
    - name: environment
      value: AzurePublicCloud
    - name: sshPublicKey
      value: c3NoLXJzYSBC
    - name: enableAcceleratedNetworking
      value: true
    - name: enablePrivateCluster
      value: false
    - name: frontendPrivateIP
      value: 20.20.20.20
    - name: customTags
      value: tagKey=tagValue
    - name: vnet
      value:
        cidr: 10.0.0.0/16
        resourceGroup: azure-vnet-resource-group
    - name: identity
      value:
        name: test-identity2
        namespace: default
    - name: controlPlane
      value:
        #count: 3
        machine:
          diskGiB: 40
          memoryMiB: 8192
          numCPUs: 2
        network:
          nameservers: 3
    - name: node
      value:
        count: 3
        machine:
          diskGiB: 40
          memoryMiB: 16384
          numCPUs: 4
        network:
          nameservers: 3
    version: v1.22.5+vmware.1
    workers:
      machineDeployments:
      - class: tkg-worker
        failureDomain: "1"
        name: md-0
        replicas: 4
      - class: tkg-worker
        failureDomain: "2"
        name: md-1
        replicas: 2
      - class: tkg-worker
        failureDomain: "3"
        name: md-2
        replicas: 1
